// step :- 1

//get
export const GET_STUDENT_PROGRESS = 'GET_STUDENT_PROGRESS';
export const GET_STUDENT_SUCESS = 'GET_STUDENT_SUCESS';
export const GET_STUDENT_ERROR = 'GET_STUDENT_ERROR';

// post

export const POST_STUDENT_PROGRESS = 'POST_STUDENT_PROGRESS';
export const POST_STUDENT_SUCESS = 'POST_STUDENT_SUCESS';
export const POST_STUDENT_ERROR = 'POST_STUDENT_ERROR';



